[package]
name = "gameboy_rs"
version = "0.2.0"
edition = "2024"
authors = ["Pontus Laestadius <pontus.laestadius@gmail.com>"]

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
human_format = "1.0.3"
